name: Build
 
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Repozytorium kas
        uses: actions/checkout@v2
 
      - name: Logowanie do Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
      - name: Konfiguracja QEMU
        uses: docker/setup-qemu-action@v2
 
      - name: Konfiguracja Docker Buildx
        uses: docker/setup-buildx-action@v2
 
      - name: Tworzenie i wypychanie obrazów Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: krissb99/pfswco:latest
